from fastapi import FastAPI
from fastapi.responses import HTMLResponse

app = FastAPI()

@app.get("/example.json")
def example():
    return {"msg": "hello world",
            "answer_to_everything": 6*7}

@app.get("/durchschnitt")
def durchschnitt(meine_json_liste_mit_zahlen):
    print(meine_json_liste_mit_zahlen)
    import json
    liste_mit_zahlen = json.loads(meine_json_liste_mit_zahlen)
    return sum(liste_mit_zahlen) / len(liste_mit_zahlen)

@app.get("/", response_class=HTMLResponse)
def index():
    return """
        <html>
         <body>
          <p>
           It works :)<br/>
           Here you find <a href="http://localhost:8000/example.json">some example json</a>
          </p>
          <p>
          Autogenerated API documentation is provided as 
          <a href="http://localhost:8000/openapi.json">openapi.json</a> and
          <a href="http://localhost:8000/docs"</a>Swagger UI</a>.
          </p>
         </body>
        </html>
    """


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app)
